#!/bin/sh

for i in $(seq ${2-5}); do
	unbuffer sudo ./t-rex-64 -f mymix.yaml --nc -d ${1-600} -c $(nproc) -m ${3-14} --arp-refresh-period 0 |
		awk '/current time/{time=$4}/Total-rx-pkt/{pkt=$3}END{printf(",%.f",pkt/time/1000)}'
done
