#!/bin/sh

for i in $(seq 0 $(($(nproc))-1)); do
	wrmsr -p$i 0x1a0 0x4000850089
done

for i in /sys/devices/system/cpu/cpu* /sys/bus/memory/devices/memory*; do
        ! [ -e "$i/node0" ] && [ -f "$i/online" ] && echo -n 0 >"$i/online"
done
