#!/bin/sh

sysctl -qw net.ipv4.ip_forward=1

ip -b - <<'EOF'
addr flush dev ens9
addr flush dev ens10
route flush dev ens9
route flush dev ens10
neigh flush dev ens9
neigh flush dev ens10
EOF

ifdown eth0

exec ip -b - <<'EOF'
addr add dev ens9 16.1.0.1/8
addr add dev ens10 20.1.0.1/8
link set dev ens9 up
link set dev ens10 up
route add 48.0.0.0/8 via 20.1.0.2
neigh add 20.1.0.2 lladdr 24:6e:96:63:81:aa dev ens10
EOF
